[package]
name = "citerion_bench"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "my_bench"
harness = false

[[bench]]
name = "search_bench"
harness = false

[[bench]]
name = "cache_bench"
harness = false